<?php
/**
 * Font Awesome 6 Free - Lista de ícones para o picker do admin
 *
 * Organizada por categoria. Apenas ícones do plano Free (solid/regular/brands).
 */

if (!defined('ABSPATH')) {
    exit;
}

function sigma_edge_get_fa_icons() {
    return [
        'Qualidade & Destaque' => [
            ['class' => 'fa-solid fa-star',           'name' => 'Estrela'],
            ['class' => 'fa-solid fa-medal',          'name' => 'Medalha'],
            ['class' => 'fa-solid fa-trophy',         'name' => 'Troféu'],
            ['class' => 'fa-solid fa-award',          'name' => 'Prêmio'],
            ['class' => 'fa-solid fa-certificate',    'name' => 'Certificado'],
            ['class' => 'fa-solid fa-crown',          'name' => 'Coroa'],
            ['class' => 'fa-solid fa-gem',            'name' => 'Gema'],
            ['class' => 'fa-solid fa-shield-halved',  'name' => 'Escudo'],
            ['class' => 'fa-solid fa-circle-check',   'name' => 'Aprovado'],
            ['class' => 'fa-solid fa-check-double',   'name' => 'Check duplo'],
            ['class' => 'fa-solid fa-thumbs-up',      'name' => 'Curtir'],
            ['class' => 'fa-solid fa-heart',          'name' => 'Coração'],
            ['class' => 'fa-solid fa-fire',           'name' => 'Fogo'],
            ['class' => 'fa-solid fa-bolt',           'name' => 'Raio'],
            ['class' => 'fa-solid fa-rocket',         'name' => 'Foguete'],
            ['class' => 'fa-solid fa-gauge-high',     'name' => 'Velocidade'],
            ['class' => 'fa-solid fa-infinity',       'name' => 'Infinito'],
            ['class' => 'fa-solid fa-ranking-star',   'name' => 'Ranking'],
            ['class' => 'fa-solid fa-circle-radiation','name' => 'Destaque'],
            ['class' => 'fa-solid fa-wand-magic-sparkles', 'name' => 'Magia'],
        ],
        'Negócio & Finanças' => [
            ['class' => 'fa-solid fa-briefcase',      'name' => 'Maleta'],
            ['class' => 'fa-solid fa-handshake',      'name' => 'Parceria'],
            ['class' => 'fa-solid fa-chart-line',     'name' => 'Gráfico linha'],
            ['class' => 'fa-solid fa-chart-bar',      'name' => 'Gráfico barra'],
            ['class' => 'fa-solid fa-chart-pie',      'name' => 'Gráfico pizza'],
            ['class' => 'fa-solid fa-dollar-sign',    'name' => 'Dólar'],
            ['class' => 'fa-solid fa-coins',          'name' => 'Moedas'],
            ['class' => 'fa-solid fa-money-bill',     'name' => 'Nota'],
            ['class' => 'fa-solid fa-sack-dollar',    'name' => 'Saco dinheiro'],
            ['class' => 'fa-solid fa-piggy-bank',     'name' => 'Cofre'],
            ['class' => 'fa-solid fa-building',       'name' => 'Prédio'],
            ['class' => 'fa-solid fa-store',          'name' => 'Loja'],
            ['class' => 'fa-solid fa-industry',       'name' => 'Indústria'],
            ['class' => 'fa-solid fa-factory',        'name' => 'Fábrica'],
            ['class' => 'fa-solid fa-warehouse',      'name' => 'Galpão'],
            ['class' => 'fa-solid fa-file-contract',  'name' => 'Contrato'],
            ['class' => 'fa-solid fa-scale-balanced', 'name' => 'Balança'],
            ['class' => 'fa-solid fa-lightbulb',      'name' => 'Ideia'],
            ['class' => 'fa-solid fa-diagram-project','name' => 'Projeto'],
            ['class' => 'fa-solid fa-sitemap',        'name' => 'Organograma'],
            ['class' => 'fa-solid fa-list-check',     'name' => 'Checklist'],
            ['class' => 'fa-solid fa-clipboard-check','name' => 'Prancheta check'],
            ['class' => 'fa-solid fa-file-signature', 'name' => 'Assinatura'],
            ['class' => 'fa-solid fa-pen-ruler',      'name' => 'Planejamento'],
        ],
        'Tecnologia & Ferramentas' => [
            ['class' => 'fa-solid fa-microchip',      'name' => 'Microchip'],
            ['class' => 'fa-solid fa-gear',           'name' => 'Engrenagem'],
            ['class' => 'fa-solid fa-gears',          'name' => 'Engrenagens'],
            ['class' => 'fa-solid fa-wrench',         'name' => 'Chave inglesa'],
            ['class' => 'fa-solid fa-screwdriver-wrench', 'name' => 'Ferramentas'],
            ['class' => 'fa-solid fa-hammer',         'name' => 'Martelo'],
            ['class' => 'fa-solid fa-laptop',         'name' => 'Laptop'],
            ['class' => 'fa-solid fa-desktop',        'name' => 'Desktop'],
            ['class' => 'fa-solid fa-mobile-screen',  'name' => 'Celular'],
            ['class' => 'fa-solid fa-server',         'name' => 'Servidor'],
            ['class' => 'fa-solid fa-database',       'name' => 'Banco dados'],
            ['class' => 'fa-solid fa-cloud',          'name' => 'Nuvem'],
            ['class' => 'fa-solid fa-cloud-arrow-up', 'name' => 'Cloud upload'],
            ['class' => 'fa-solid fa-wifi',           'name' => 'Wi-Fi'],
            ['class' => 'fa-solid fa-robot',          'name' => 'Robô'],
            ['class' => 'fa-solid fa-code',           'name' => 'Código'],
            ['class' => 'fa-solid fa-terminal',       'name' => 'Terminal'],
            ['class' => 'fa-solid fa-print',          'name' => 'Impressora'],
            ['class' => 'fa-solid fa-plug',           'name' => 'Tomada'],
            ['class' => 'fa-solid fa-bolt-lightning', 'name' => 'Energia'],
            ['class' => 'fa-solid fa-satellite-dish', 'name' => 'Antena'],
            ['class' => 'fa-solid fa-toolbox',        'name' => 'Caixa ferramentas'],
            ['class' => 'fa-solid fa-layer-group',    'name' => 'Camadas'],
            ['class' => 'fa-solid fa-sliders',        'name' => 'Controles'],
        ],
        'Comunicação & Contato' => [
            ['class' => 'fa-solid fa-envelope',       'name' => 'E-mail'],
            ['class' => 'fa-solid fa-phone',          'name' => 'Telefone'],
            ['class' => 'fa-solid fa-comment',        'name' => 'Comentário'],
            ['class' => 'fa-solid fa-comments',       'name' => 'Comentários'],
            ['class' => 'fa-solid fa-message',        'name' => 'Mensagem'],
            ['class' => 'fa-solid fa-bullhorn',       'name' => 'Megafone'],
            ['class' => 'fa-solid fa-headset',        'name' => 'Suporte'],
            ['class' => 'fa-solid fa-video',          'name' => 'Vídeo'],
            ['class' => 'fa-solid fa-bell',           'name' => 'Notificação'],
            ['class' => 'fa-solid fa-rss',            'name' => 'Feed'],
            ['class' => 'fa-solid fa-share-nodes',    'name' => 'Compartilhar'],
            ['class' => 'fa-solid fa-paper-plane',    'name' => 'Enviar'],
            ['class' => 'fa-solid fa-at',             'name' => 'Arroba'],
            ['class' => 'fa-solid fa-globe',          'name' => 'Web'],
            ['class' => 'fa-brands fa-whatsapp',      'name' => 'WhatsApp'],
            ['class' => 'fa-brands fa-instagram',     'name' => 'Instagram'],
            ['class' => 'fa-brands fa-facebook-f',    'name' => 'Facebook'],
            ['class' => 'fa-brands fa-linkedin-in',   'name' => 'LinkedIn'],
            ['class' => 'fa-brands fa-youtube',       'name' => 'YouTube'],
            ['class' => 'fa-brands fa-x-twitter',     'name' => 'X / Twitter'],
        ],
        'Localização & Logística' => [
            ['class' => 'fa-solid fa-location-dot',   'name' => 'Localização'],
            ['class' => 'fa-solid fa-map',            'name' => 'Mapa'],
            ['class' => 'fa-solid fa-map-location-dot','name' => 'Mapa marcador'],
            ['class' => 'fa-solid fa-compass',        'name' => 'Bússola'],
            ['class' => 'fa-solid fa-route',          'name' => 'Rota'],
            ['class' => 'fa-solid fa-car',            'name' => 'Carro'],
            ['class' => 'fa-solid fa-truck',          'name' => 'Caminhão'],
            ['class' => 'fa-solid fa-truck-fast',     'name' => 'Entrega rápida'],
            ['class' => 'fa-solid fa-box',            'name' => 'Caixa'],
            ['class' => 'fa-solid fa-boxes-stacked',  'name' => 'Estoque'],
            ['class' => 'fa-solid fa-plane',          'name' => 'Avião'],
            ['class' => 'fa-solid fa-ship',           'name' => 'Navio'],
            ['class' => 'fa-solid fa-bicycle',        'name' => 'Bicicleta'],
            ['class' => 'fa-solid fa-house',          'name' => 'Casa'],
            ['class' => 'fa-solid fa-city',           'name' => 'Cidade'],
            ['class' => 'fa-solid fa-flag',           'name' => 'Bandeira'],
        ],
        'Pessoas & Equipe' => [
            ['class' => 'fa-solid fa-user',           'name' => 'Usuário'],
            ['class' => 'fa-solid fa-users',          'name' => 'Equipe'],
            ['class' => 'fa-solid fa-user-tie',       'name' => 'Profissional'],
            ['class' => 'fa-solid fa-user-check',     'name' => 'Aprovado'],
            ['class' => 'fa-solid fa-user-gear',      'name' => 'Configuração'],
            ['class' => 'fa-solid fa-person',         'name' => 'Pessoa'],
            ['class' => 'fa-solid fa-people-group',   'name' => 'Grupo'],
            ['class' => 'fa-solid fa-id-card',        'name' => 'Carteirinha'],
            ['class' => 'fa-solid fa-address-book',   'name' => 'Agenda'],
            ['class' => 'fa-solid fa-graduation-cap', 'name' => 'Formatura'],
            ['class' => 'fa-solid fa-chalkboard-user','name' => 'Treinamento'],
            ['class' => 'fa-solid fa-hand-holding-heart', 'name' => 'Cuidado'],
            ['class' => 'fa-solid fa-hands-holding-circle', 'name' => 'Comunidade'],
            ['class' => 'fa-solid fa-handshake-angle','name' => 'Ajuda'],
        ],
        'Segurança' => [
            ['class' => 'fa-solid fa-lock',           'name' => 'Cadeado'],
            ['class' => 'fa-solid fa-lock-open',      'name' => 'Desbloqueado'],
            ['class' => 'fa-solid fa-key',            'name' => 'Chave'],
            ['class' => 'fa-solid fa-shield',         'name' => 'Escudo'],
            ['class' => 'fa-solid fa-shield-heart',   'name' => 'Proteção'],
            ['class' => 'fa-solid fa-eye',            'name' => 'Vigilância'],
            ['class' => 'fa-solid fa-fingerprint',    'name' => 'Digital'],
            ['class' => 'fa-solid fa-user-shield',    'name' => 'Proteção usuário'],
            ['class' => 'fa-solid fa-circle-exclamation', 'name' => 'Atenção'],
            ['class' => 'fa-solid fa-triangle-exclamation', 'name' => 'Aviso'],
            ['class' => 'fa-solid fa-ban',            'name' => 'Proibido'],
            ['class' => 'fa-solid fa-fire-extinguisher', 'name' => 'Extintor'],
            ['class' => 'fa-solid fa-helmet-safety',  'name' => 'Capacete'],
            ['class' => 'fa-solid fa-vest',           'name' => 'Colete'],
        ],
        'Natureza & Sustentabilidade' => [
            ['class' => 'fa-solid fa-leaf',           'name' => 'Folha'],
            ['class' => 'fa-solid fa-tree',           'name' => 'Árvore'],
            ['class' => 'fa-solid fa-seedling',       'name' => 'Muda'],
            ['class' => 'fa-solid fa-sun',            'name' => 'Sol'],
            ['class' => 'fa-solid fa-droplet',        'name' => 'Gota'],
            ['class' => 'fa-solid fa-wind',           'name' => 'Vento'],
            ['class' => 'fa-solid fa-recycle',        'name' => 'Reciclagem'],
            ['class' => 'fa-solid fa-earth-americas', 'name' => 'Terra'],
            ['class' => 'fa-solid fa-solar-panel',    'name' => 'Painel solar'],
            ['class' => 'fa-solid fa-snowflake',      'name' => 'Floco de neve'],
            ['class' => 'fa-solid fa-temperature-low','name' => 'Temperatura baixa'],
            ['class' => 'fa-solid fa-temperature-high','name' => 'Temperatura alta'],
        ],
        'Saúde & Bem-estar' => [
            ['class' => 'fa-solid fa-heart-pulse',    'name' => 'Batimento'],
            ['class' => 'fa-solid fa-stethoscope',    'name' => 'Estetoscópio'],
            ['class' => 'fa-solid fa-kit-medical',    'name' => 'Kit médico'],
            ['class' => 'fa-solid fa-pills',          'name' => 'Remédios'],
            ['class' => 'fa-solid fa-hospital',       'name' => 'Hospital'],
            ['class' => 'fa-solid fa-dumbbell',       'name' => 'Haltere'],
            ['class' => 'fa-solid fa-apple-whole',    'name' => 'Maçã'],
            ['class' => 'fa-solid fa-spa',            'name' => 'Spa'],
            ['class' => 'fa-solid fa-person-running', 'name' => 'Corrida'],
            ['class' => 'fa-solid fa-brain',          'name' => 'Mente'],
        ],
        'Símbolos & Setas' => [
            ['class' => 'fa-solid fa-circle',         'name' => 'Círculo'],
            ['class' => 'fa-solid fa-circle-dot',     'name' => 'Círculo ponto'],
            ['class' => 'fa-solid fa-square',         'name' => 'Quadrado'],
            ['class' => 'fa-solid fa-diamond',        'name' => 'Diamante'],
            ['class' => 'fa-solid fa-minus',          'name' => 'Traço'],
            ['class' => 'fa-solid fa-plus',           'name' => 'Mais'],
            ['class' => 'fa-solid fa-check',          'name' => 'Check'],
            ['class' => 'fa-solid fa-xmark',          'name' => 'X'],
            ['class' => 'fa-solid fa-asterisk',       'name' => 'Asterisco'],
            ['class' => 'fa-solid fa-hashtag',        'name' => 'Hashtag'],
            ['class' => 'fa-solid fa-percent',        'name' => 'Porcentagem'],
            ['class' => 'fa-solid fa-arrow-right',    'name' => 'Seta direita'],
            ['class' => 'fa-solid fa-arrow-up',       'name' => 'Seta cima'],
            ['class' => 'fa-solid fa-arrow-trend-up', 'name' => 'Tendência alta'],
            ['class' => 'fa-solid fa-angles-right',   'name' => 'Dupla seta'],
            ['class' => 'fa-solid fa-caret-right',    'name' => 'Seta pequena'],
            ['class' => 'fa-solid fa-expand',         'name' => 'Expandir'],
            ['class' => 'fa-solid fa-tag',            'name' => 'Tag'],
            ['class' => 'fa-solid fa-tags',           'name' => 'Tags'],
            ['class' => 'fa-solid fa-star-of-life',   'name' => 'Estrela vida'],
        ],
    ];
}
